### ISSUE TITLE
Main-master branch inconsistency

### ISSUE THREAD

**Issue by DraTeots** [eic/ip6#1]
ecce repository has 'main' branch but ip6 repository has 'master' branch. Perfectionist hell

**Comment by DraTeots** [comment]
Sigh... Ok then.... Just know it and live with it!

**Comment by wdconinc** [comment]
Sorry, but changing a default branch name is invasive for all current users (and potentially error prone and confusing). We shouldn't do that for mere esthetic reasons.

**Comment by DraTeots** [comment]
I understand. Just can't unsee this.

![devil](https://cdn.iconscout.com/icon/premium/png-64-thumb/devil-face-emoji-1718964-1461917.png)

If seriously, I hope ip6 will be merged into the detector as living in a separate repo is now has much less points

**Comment by wdconinc** [comment]
Maybe. A lot of infrastructure is built on the two repo model. Upsetting that is not a high priority.
