### ISSUE TITLE
inconsistent naming of CylindricalDipoleMagnet

### ISSUE THREAD

**Issue by faustus123** [eic/ip6#2]
It seems the definition of the CylindricalDipoleMagnet linked below declares it as "ip6_CylindricalDipoleMagnet" which is not consistent with the "CylindricalDipoleMagnet" type used in the ip6/far_backward/magnets.xml. I'm unable to read in the geometry unless "ip6_" is added to the type in the XML. I'm not sure if these are supposed to be the same, or there is some other DECLARE_DETELEMENT(CylindricalDipoleMagnet, ...) statement that is not being found.

https://github.com/eic/ip6/blob/d5c9c26dc5b64a5b6db95d523202d4e20d4d13ce/src/CylindricalDipoleMagnet_geo.cpp#L104

**Comment by wdconinc** [comment]
Thanks for catching this. These should be replaced by ip6_CylindricalDipoleMagnet. The original was (is) part of the NPDet collection which we should not depend on.

**Comment by wdconinc** [comment]
https://eicweb.phy.anl.gov/EIC/detectors/ip6/-/merge_requests/118

**Comment by wdconinc** [comment]
This has now been merged. A set of tests based on a completely separate development environment from eic-shell (namely LCG) was added for both ecce and ip6 repositories to ensure we don't have any other 'hidden' dependencies that are remaining or may be introduced in the future. See e.g. https://github.com/eic/ip6/actions/runs/2727875490.
